apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocm-controllers
  namespace: default
spec:
  interval: 30s
  url: https://github.com/open-component-model/ocm-k8s-toolkit
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ocm-controllers
spec:
  targetNamespace: default
  interval: 30s
  prune: true
  sourceRef:
    kind: GitRepository
    name: ocm-controllers
  path: "config/default"
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: ghcr.io/open-component-model/ocm-k8s-toolkit:latest
      target:
        kind: Deployment
        name: .*
